packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@biomejs/biome': 2.4.13
  '@markdoc/markdoc': 0.5.7
  '@sveltejs/kit': 2.59.1
  '@sveltejs/vite-plugin-svelte': 5.1.1
  '@tanstack/react-router': 1.169.2
  '@tanstack/react-start': 1.167.65
  '@types/node': 25.6.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 6.0.1
  '@vitejs/plugin-vue': 6.0.6
  astro: 6.3.2
  marked: 18.0.3
  react: 19.2.5
  react-dom: 19.2.5
  react-router: 7.15.0
  svelte: 5.55.5
  tsup: 8.5.1
  typedoc: 0.28.19
  typescript: 6.0.3
  vite: 8.0.12
  vitest: 3.0.4
  vue: 3.5.13
