packages:
  - docs
  - docs/compiler
  - e2e
  - e2e/sandbox
  - examples/*
  - packages/*

allowBuilds:
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
  sharp: false
  workerd: false

catalogMode: strict

minimumReleaseAge: 10080

savePrefix: ''

trustLockfile: true

updateConfig:
  ignoreDependencies:
    - '@types/vscode'
    - h3
    - typescript

catalog:
  '@arethetypeswrong/cli': 0.18.5
  '@arethetypeswrong/core': 0.18.5
  '@astrojs/check': 0.9.10
  '@astrojs/compiler-rs': 0.5.0
  '@astrojs/node': 11.1.6
  '@biomejs/biome': 2.5.14
  '@changesets/changelog-github': 1.0.1
  '@changesets/cli': 3.0.3
  '@fast-check/vitest': 0.5.0
  '@markdoc/markdoc': 0.5.10
  '@nuxt/kit': 4.5.2
  '@nuxt/nitro-server': 4.5.2
  '@playwright/test': 1.63.0
  '@react-router/dev': 8.4.0
  '@react-router/node': 8.4.0
  '@react-router/serve': 8.4.0
  '@sveltejs/adapter-node': 5.5.7
  '@sveltejs/kit': 2.70.3
  '@sveltejs/package': 2.5.8
  '@sveltejs/vite-plugin-svelte': 7.3.1
  '@tanstack/react-router': 1.170.39
  '@tanstack/react-start': 1.168.58
  '@testing-library/react': 16.3.3
  '@testing-library/svelte': 5.4.2
  '@testing-library/vue': 8.1.0
  '@types/estree': 1.0.9
  '@types/estree-jsx': 1.0.5
  '@types/mocha': 10.0.10
  '@types/node': 26.6.2
  '@types/picomatch': 4.0.3
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  '@types/vscode': 1.125.0
  '@typescript/typescript6': 6.0.2
  '@vitejs/plugin-react': 6.1.1
  '@vitejs/plugin-vue': 6.0.9
  '@vitest/coverage-v8': 4.1.10
  '@vscode/test-cli': 0.0.15
  '@vscode/test-electron': 3.1.0
  '@vscode/vsce': 3.9.2
  '@vue/compiler-core': 3.5.43
  '@vue/compiler-sfc': 3.5.43
  astro: 7.3.5
  h3: 1.15.11
  'happy-dom': 20.14.5
  isbot: 5.2.2
  jiti: 2.7.0
  knip: 6.38.0
  'magic-string': 1.4.2
  nitropack: 2.13.4
  nuxt: 4.5.2
  picomatch: 4.0.7
  publint: 0.3.24
  react: 19.3.0
  react-dom: 19.3.0
  react-router: 8.4.0
  svelte: 5.57.1
  svelte-check: 4.7.6
  tsdown: 0.23.0
  tsx: 4.23.15
  typescript: 6.0.3
  vite: 8.3.1
  vitest: 4.1.10
  vue: 3.5.43
  vue-tsc: 3.3.11
  wrangler: 4.140.0
