import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/internal/index.ts',
    'src/react/index.ts',
    'src/vue/index.ts',
    'src/svelte/index.ts',
    'src/vite/plugin.ts',
    'src/adapter/index.ts',
    'src/adapter/astro.ts',
    'src/adapter/nuxt.ts',
    'src/adapter/react-router.ts',
    'src/adapter/sveltekit.ts',
    'src/adapter/tanstack-start.ts',
    'src/translator/index.ts',
    'src/translator/anthropic.ts',
    'src/translator/openai.ts',
    'src/translator/gemini.ts',
    'src/translator/ollama.ts',
    'src/cli/run.ts',
  ],
  format: 'esm',
  dts: true,
  clean: true,
  splitting: false,
  outDir: 'dist',
  target: 'node22',
  external: [
    'nitropack',
    'nitropack/runtime',
    'nitropack/types',
    '@sveltejs/kit',
    'astro',
    'astro:middleware',
    'react',
    'react-router',
    'vite',
    'virtual:yapyak',
    'vue',
  ],
});
