export const KEY_MAP = {
  alt: 'Alt',
  backspace: 'Backspace',
  control: 'Control',
  delete: 'Delete',
  down: 'ArrowDown',
  end: 'End',
  enter: 'Enter',
  escape: 'Escape',
  home: 'Home',
  left: 'ArrowLeft',
  meta: 'Meta',
  pageDown: 'PageDown',
  pageUp: 'PageUp',
  right: 'ArrowRight',
  shift: 'Shift',
  space: ' ',
  tab: 'Tab',
  up: 'ArrowUp',
} as const;
