/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as GuideIndexRouteImport } from './routes/guide.index'
import { Route as GuideSplatRouteImport } from './routes/guide.$'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'
import { Route as ReferenceSplatRouteImport } from './routes/reference.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuideRoute,
} as any)
const GuideSplatRoute = GuideSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => GuideRoute,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferenceRoute,
} as any)
const ReferenceSplatRoute = ReferenceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ReferenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/reference': typeof ReferenceRouteWithChildren
  '/guide/$': typeof GuideSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/guide/': typeof GuideIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide/$': typeof GuideSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/guide': typeof GuideIndexRoute
  '/reference': typeof ReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/reference': typeof ReferenceRouteWithChildren
  '/guide/$': typeof GuideSplatRoute
  '/reference/$': typeof ReferenceSplatRoute
  '/guide/': typeof GuideIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/reference'
    | '/guide/$'
    | '/reference/$'
    | '/guide/'
    | '/reference/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide/$' | '/reference/$' | '/guide' | '/reference'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/reference'
    | '/guide/$'
    | '/reference/$'
    | '/guide/'
    | '/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRouteWithChildren
  ReferenceRoute: typeof ReferenceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/$': {
      id: '/guide/$'
      path: '/$'
      fullPath: '/guide/$'
      preLoaderRoute: typeof GuideSplatRouteImport
      parentRoute: typeof GuideRoute
    }
    '/reference/': {
      id: '/reference/'
      path: '/'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof ReferenceRoute
    }
    '/reference/$': {
      id: '/reference/$'
      path: '/$'
      fullPath: '/reference/$'
      preLoaderRoute: typeof ReferenceSplatRouteImport
      parentRoute: typeof ReferenceRoute
    }
  }
}

interface GuideRouteChildren {
  GuideSplatRoute: typeof GuideSplatRoute
  GuideIndexRoute: typeof GuideIndexRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideSplatRoute: GuideSplatRoute,
  GuideIndexRoute: GuideIndexRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

interface ReferenceRouteChildren {
  ReferenceSplatRoute: typeof ReferenceSplatRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

const ReferenceRouteChildren: ReferenceRouteChildren = {
  ReferenceSplatRoute: ReferenceSplatRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}

const ReferenceRouteWithChildren = ReferenceRoute._addFileChildren(
  ReferenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRouteWithChildren,
  ReferenceRoute: ReferenceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
