/**
 * The register. Declares augmentation slots for narrowing yapyak's locale-related types.
 *
 * @remarks
 * Augment from a `.d.ts` file in the consuming project (typically `.yapyak/types.d.ts`, auto-generated by `@yapyak/vite`) to narrow {@link Locale} from `string` to a literal union. Without augmentation, all locale-typed APIs fall back to `string`.
 *
 * @example Narrow Locale via module augmentation
 * ```ts
 * declare module 'yapyak' {
 *   interface Register {
 *     Locale: 'en' | 'sv' | 'da';
 *   }
 * }
 * ```
 */
// biome-ignore lint/style/useConsistentTypeDefinitions: yap yap yap
// biome-ignore lint/suspicious/noEmptyInterface: yap yap yap
export interface Register {}

/**
 * The locale. Narrows to a project's configured locales when {@link Register} is augmented; falls back to `string` otherwise.
 *
 * @example Use Locale in a function signature
 * ```ts
 * import type { Locale } from 'yapyak';
 *
 * function logSwitch(locale: Locale): void {
 *   console.log('switching to', locale);
 * }
 * ```
 */
export type Locale = Register extends {
  // biome-ignore lint/style/useNamingConvention: yap yap yap
  Locale: infer L extends string;
}
  ? L
  : string;
