/**
 * Module augmentation hook for narrowing yapyak's locale-related types to a project's configured locales.
 *
 * @remarks
 * Augment this interface from a `.d.ts` file in the consuming project (typically `.yapyak/types.d.ts`, auto-generated by `@yapyak/vite`) to narrow {@link Locale} from `string` to a literal union. Without augmentation, all locale-typed APIs fall back to `string`.
 *
 * @example Narrow `Locale` via module augmentation
 * ```ts [.yapyak/types.d.ts]
 * declare module 'yapyak' {
 *   interface Register {
 *     Locale: 'en' | 'sv' | 'dk';
 *   }
 * }
 * ```
 */
// biome-ignore lint/suspicious/noEmptyInterface: empty by design — populated via module augmentation
export interface Register {}

/**
 * The locale string. Narrows to a project's configured locales when {@link Register} is augmented; falls back to `string` otherwise.
 *
 * @example Use `Locale` in a function signature
 * ```ts
 * import type { Locale } from 'yapyak';
 *
 * function logSwitch(locale: Locale): void {
 *   console.log('switching to', locale);
 * }
 * ```
 */
export type Locale = Register extends { Locale: infer L extends string }
  ? L
  : string;
