export {
  type AutoTranslateOptions,
  type AutoTranslateResult,
  autoTranslate,
  CorruptLocaleFileError,
  type DiscoverLocalesOptions,
  type DiscoverLocalesResult,
  detectAtIssues,
  detectRenames,
  discoverLocales,
  type InvariantViolation,
  type LocaleData,
  type LocaleFile,
  type LocaleIssue,
  type LocaleValidation,
  type LocaleWarning,
  type MessagePosition,
  type MigrateLocalesOptions,
  type MigrateLocalesResult,
  migrateLocales,
  type ReadLocaleDataOptions,
  type RenameEntry,
  readLocaleData,
  readLocaleFile,
  type SyncLocaleFilesOptions,
  stringifyCanonical,
  syncLocaleFiles,
  type ValidateIcuPairsInput,
  type ValidateLocaleFileInput,
  validateIcuPairs,
  validateLocaleCode,
  validateLocaleFile,
  type WriteLocaleFileInput,
  writeLocaleFile,
  YapyakInvariantError,
} from './catalog';
export {
  DEFAULT_EXCLUDE,
  DEFAULT_INCLUDE,
  type WalkedFile,
  type WalkSourceFilesOptions,
  walkSourceFiles,
} from './io';
export {
  astroProcessor,
  type Binding,
  type BindingTable,
  type CallSite,
  type CallSiteContext,
  type CreateDiagnosticInput,
  createDiagnostic,
  type Diagnostic,
  type DiagnosticCode,
  discoverCalls,
  type ElisionContext,
  type ExtractedMessage,
  type ExtractFileRequest,
  type ExtractFileResult,
  extractFile,
  type Fragment,
  getProcessor,
  type IcuIssue,
  type Location,
  type ParsedArguments,
  type ParsedMessage,
  type ParsedParams,
  type Placeholder,
  type PlaceholderKind,
  type Position,
  type Processor,
  type ProcessorKind,
  parseArguments,
  parsePlaceholders,
  type Range,
  type ResolveBindingsOptions,
  resolveBindings,
  resolveCallSiteContext,
  resolveProcessorKind,
  type Scope,
  svelteProcessor,
  type TransformFileRequest,
  type TransformFileResult,
  toMessageId,
  transformFile,
  vanillaProcessor,
  vueProcessor,
} from './parser';
