/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferenceRouteRouteImport } from './routes/reference/route'
import { Route as GuideRouteRouteImport } from './routes/guide/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference/index'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as ReferenceSlugRouteImport } from './routes/reference/$slug'
import { Route as GuideSlugRouteImport } from './routes/guide/$slug'

const ReferenceRouteRoute = ReferenceRouteRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRouteRoute = GuideRouteRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferenceRouteRoute,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuideRouteRoute,
} as any)
const ReferenceSlugRoute = ReferenceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReferenceRouteRoute,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuideRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteRouteWithChildren
  '/reference': typeof ReferenceRouteRouteWithChildren
  '/guide/$slug': typeof GuideSlugRoute
  '/reference/$slug': typeof ReferenceSlugRoute
  '/guide/': typeof GuideIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/reference/$slug': typeof ReferenceSlugRoute
  '/guide': typeof GuideIndexRoute
  '/reference': typeof ReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteRouteWithChildren
  '/reference': typeof ReferenceRouteRouteWithChildren
  '/guide/$slug': typeof GuideSlugRoute
  '/reference/$slug': typeof ReferenceSlugRoute
  '/guide/': typeof GuideIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/reference'
    | '/guide/$slug'
    | '/reference/$slug'
    | '/guide/'
    | '/reference/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide/$slug' | '/reference/$slug' | '/guide' | '/reference'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/reference'
    | '/guide/$slug'
    | '/reference/$slug'
    | '/guide/'
    | '/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRouteRoute: typeof GuideRouteRouteWithChildren
  ReferenceRouteRoute: typeof ReferenceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/guide/': {
      id: '/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/reference/$slug': {
      id: '/reference/$slug'
      path: '/$slug'
      fullPath: '/reference/$slug'
      preLoaderRoute: typeof ReferenceSlugRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof GuideRouteRoute
    }
  }
}

interface GuideRouteRouteChildren {
  GuideSlugRoute: typeof GuideSlugRoute
  GuideIndexRoute: typeof GuideIndexRoute
}

const GuideRouteRouteChildren: GuideRouteRouteChildren = {
  GuideSlugRoute: GuideSlugRoute,
  GuideIndexRoute: GuideIndexRoute,
}

const GuideRouteRouteWithChildren = GuideRouteRoute._addFileChildren(
  GuideRouteRouteChildren,
)

interface ReferenceRouteRouteChildren {
  ReferenceSlugRoute: typeof ReferenceSlugRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

const ReferenceRouteRouteChildren: ReferenceRouteRouteChildren = {
  ReferenceSlugRoute: ReferenceSlugRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}

const ReferenceRouteRouteWithChildren = ReferenceRouteRoute._addFileChildren(
  ReferenceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRouteRoute: GuideRouteRouteWithChildren,
  ReferenceRouteRoute: ReferenceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
