/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteRouteImport } from './routes/guide/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as GuideSlugRouteImport } from './routes/guide/$slug'

const GuideRouteRoute = GuideRouteRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuideRouteRoute,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuideRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteRouteWithChildren
  '/guide/$slug': typeof GuideSlugRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/guide': typeof GuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteRouteWithChildren
  '/guide/$slug': typeof GuideSlugRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/guide/$slug' | '/guide/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide/$slug' | '/guide'
  id: '__root__' | '/' | '/guide' | '/guide/$slug' | '/guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRouteRoute: typeof GuideRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof GuideRouteRoute
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof GuideRouteRoute
    }
  }
}

interface GuideRouteRouteChildren {
  GuideSlugRoute: typeof GuideSlugRoute
  GuideIndexRoute: typeof GuideIndexRoute
}

const GuideRouteRouteChildren: GuideRouteRouteChildren = {
  GuideSlugRoute: GuideSlugRoute,
  GuideIndexRoute: GuideIndexRoute,
}

const GuideRouteRouteWithChildren = GuideRouteRoute._addFileChildren(
  GuideRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRouteRoute: GuideRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
