export interface GenerateTypesOptions {
  defaultLocale: string;
  framework: 'react' | 'vue' | 'svelte';
  locales: string[];
  moduleName: string;
  translations: Record<string, Record<string, string>>;
}

export function generateTypes(options: GenerateTypesOptions): string {
  const { framework, locales, moduleName, translations } = options;
  const localeUnion = locales
    .map((locale) => JSON.stringify(locale))
    .join(' | ');

  const knownSources = new Set<string>();
  for (const fileTranslations of Object.values(translations)) {
    for (const source of Object.keys(fileTranslations)) {
      knownSources.add(source);
    }
  }
  const knownSourceUnion =
    knownSources.size > 0
      ? [...knownSources].map((s) => JSON.stringify(s)).join(' | ')
      : 'never';

  const fileIds = Object.keys(translations).sort();

  const lines: string[] = [];
  lines.push(`// Auto-generated by yapyak/vite. Do not edit.`);
  lines.push('');
  lines.push(`declare module ${JSON.stringify(moduleName)} {`);
  lines.push(
    `  import type { ExtractParams, LocaleModule, MessageFunction } from 'yapyak';`,
  );

  if (framework === 'svelte') {
    lines.push(`  import type { ReactiveLocale } from 'yapyak/svelte';`);
  } else if (framework === 'vue') {
    lines.push(`  import type { WritableComputedRef } from 'vue';`);
    lines.push(`  import type { YapyakPlugin } from 'yapyak/vue';`);
  } else {
    lines.push(`  import type {`);
    lines.push(`    Intl,`);
    lines.push(`    IntlProviderProps,`);
    lines.push(`  } from 'yapyak/react';`);
    lines.push(`  import type { FC } from 'react';`);
  }
  lines.push('');
  lines.push(`  export type Locale = ${localeUnion};`);
  lines.push('');
  lines.push(`  export type KnownSource = ${knownSourceUnion};`);
  lines.push('');
  lines.push(`  export const t: <T extends KnownSource | (string & {})>(`);
  lines.push(`    source: T,`);
  lines.push(`    ...args: ExtractParams<T> extends Record<string, never>`);
  lines.push(`      ? []`);
  lines.push(`      : [params: ExtractParams<T>]`);
  lines.push(`  ) => string;`);
  lines.push('');

  if (framework === 'svelte') {
    lines.push(`  export const locale: ReactiveLocale & { current: Locale };`);
  } else if (framework === 'vue') {
    lines.push(`  export const yapyak: YapyakPlugin;`);
    lines.push(`  export const useLocale: () => WritableComputedRef<Locale>;`);
  } else {
    lines.push(`  export const IntlProvider: FC<IntlProviderProps>;`);
    lines.push(
      `  export const useLocale: () => readonly [Locale, (locale: Locale) => Promise<void>];`,
    );
    lines.push(`  export const useTranslation: Intl['useTranslation'];`);
  }
  lines.push('');

  if (fileIds.length > 0) {
    lines.push(`  type Messages = {`);
    for (const fileId of fileIds) {
      const fileTranslations = translations[fileId] ?? {};
      const sources = Object.keys(fileTranslations).sort();
      lines.push(`    ${JSON.stringify(fileId)}: {`);
      for (const source of sources) {
        lines.push(`      ${JSON.stringify(source)}: MessageFunction;`);
      }
      lines.push(`    };`);
    }
    lines.push(`  };`);
    lines.push(`  export const messages: Record<Locale, Messages>;`);
  } else {
    lines.push(`  export const messages: Record<Locale, LocaleModule>;`);
  }

  lines.push('');
  lines.push(`  export const setLocale: (locale: Locale) => Promise<void>;`);
  lines.push(`  export const getLocale: () => Locale;`);
  lines.push('');

  if (framework === 'svelte') {
    lines.push(`  import type { Intl as SvelteIntl } from 'yapyak/svelte';`);
    lines.push(`  const intl: SvelteIntl;`);
  } else if (framework === 'vue') {
    lines.push(`  const intl: YapyakPlugin;`);
  } else {
    lines.push(`  const intl: Intl;`);
  }
  lines.push(`  export default intl;`);
  lines.push(`}`);
  lines.push('');
  lines.push(`declare module ${JSON.stringify(`${moduleName}/locale-*`)} {`);
  lines.push(`  import type { LocaleModule } from 'yapyak';`);
  lines.push(`  const module: LocaleModule;`);
  lines.push(`  export default module;`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}
