import { compileMessage } from '../compiler/compile-message.js';
import { createIntlInstances } from '../compiler/intl-instances.js';

export interface MessageEntry {
  componentName?: string;
  fileId: string;
  hash: string;
  line?: number;
  snippet?: string;
  source: string;
}

export interface GenerateMessagesModuleOptions {
  defaultLocale: string;
  locales: string[];
  messages: MessageEntry[];
  translations: Record<string, Record<string, Record<string, string>>>;
}

export function generateMessagesModule(
  options: GenerateMessagesModuleOptions,
): string {
  const { defaultLocale, locales, messages, translations } = options;
  const intl = createIntlInstances();
  const lines: string[] = [];

  lines.push(`// Auto-generated by yapyak. Do not edit.`);
  lines.push(`import { getLocale as _getLocale } from 'yapyak';`);
  lines.push('');
  lines.push(`if (import.meta.hot) {`);
  lines.push(`  import.meta.hot.accept(() => {`);
  lines.push(
    `    if (typeof window !== 'undefined' && window.__yapyakNotify) window.__yapyakNotify();`,
  );
  lines.push(`  });`);
  lines.push(`}`);
  lines.push(
    `const _track = (h) => { if (typeof window !== 'undefined' && window.__yapyakSeen) window.__yapyakSeen.add(h); };`,
  );
  lines.push(
    `if (import.meta.env.DEV && typeof window !== 'undefined' && !window.__yapyakImpl) window.__yapyakImpl = {};`,
  );
  lines.push('');

  const declarationsSlot = lines.length;
  lines.push('');

  for (const entry of messages) {
    const localeFns: string[] = [];
    for (const locale of locales) {
      const localeTranslations = translations[locale];
      const fileTranslations = localeTranslations?.[entry.fileId];
      const translation =
        fileTranslations?.[entry.source] ??
        translations[defaultLocale]?.[entry.fileId]?.[entry.source] ??
        entry.source;
      const fn = compileMessage(translation, locale, intl);
      localeFns.push(`  ${JSON.stringify(locale)}: ${fn},`);
    }

    lines.push(`const _v_${entry.hash} = {`);
    for (const fn of localeFns) {
      lines.push(fn);
    }
    lines.push(`};`);
    lines.push(
      `const _impl_${entry.hash} = (p) => _v_${entry.hash}[_getLocale()](p);`,
    );
    lines.push(
      `if (import.meta.env.DEV && typeof window !== 'undefined') window.__yapyakImpl[${JSON.stringify(entry.hash)}] = _impl_${entry.hash};`,
    );
    lines.push(`export const _m_${entry.hash} = import.meta.env.DEV`);
    lines.push(
      `  ? (p) => { _track(${JSON.stringify(entry.hash)}); return typeof window !== 'undefined' ? window.__yapyakImpl[${JSON.stringify(entry.hash)}](p) : _impl_${entry.hash}(p); }`,
    );
    lines.push(`  : _impl_${entry.hash};`);
    lines.push('');
  }

  if (intl.declarations.length > 0) {
    const declarations = ['', ...intl.declarations, ''];
    lines.splice(declarationsSlot, 1, ...declarations);
  }

  return lines.join('\n');
}
