import { compileMessage } from '../compiler/compile-message.js';
import { createIntlInstances } from '../compiler/intl-instances.js';

export interface MessageEntry {
  fileId: string;
  hash: string;
  source: string;
}

export interface GenerateMessagesModuleOptions {
  defaultLocale: string;
  locales: string[];
  messages: MessageEntry[];
  translations: Record<string, Record<string, Record<string, string>>>;
}

export function generateMessagesModule(
  options: GenerateMessagesModuleOptions,
): string {
  const { defaultLocale, locales, messages, translations } = options;
  const intl = createIntlInstances();
  const lines: string[] = [];

  lines.push(`// Auto-generated by yapyak. Do not edit.`);
  lines.push(`import { getLocale as _getLocale } from 'yapyak';`);
  lines.push('');

  const declarationsSlot = lines.length;
  lines.push('');

  for (const entry of messages) {
    const localeFns: string[] = [];
    for (const locale of locales) {
      const localeTranslations = translations[locale];
      const fileTranslations = localeTranslations?.[entry.fileId];
      const translation =
        fileTranslations?.[entry.source] ??
        translations[defaultLocale]?.[entry.fileId]?.[entry.source] ??
        entry.source;
      const fn = compileMessage(translation, locale, intl);
      localeFns.push(`  ${JSON.stringify(locale)}: ${fn},`);
    }

    lines.push(`const _v_${entry.hash} = {`);
    for (const fn of localeFns) {
      lines.push(fn);
    }
    lines.push(`};`);
    lines.push(
      `export const _m_${entry.hash} = (p) => _v_${entry.hash}[_getLocale()](p);`,
    );
    lines.push('');
  }

  if (intl.declarations.length > 0) {
    const declarations = ['', ...intl.declarations, ''];
    lines.splice(declarationsSlot, 1, ...declarations);
  }

  return lines.join('\n');
}
