import { compileMessage } from './compile-message.js';
import { createIntlInstances } from './intl-instances.js';
import { stableHash } from './stable-hash.js';

export interface CompileLocaleOptions {
  locale: string;
  translations: Record<string, Record<string, string>>;
  usedFiles?: Set<string>;
}

export interface CompiledLocale {
  code: string;
  fileCount: number;
  messageCount: number;
}

export class CompileError extends Error {
  locale: string;
  fileId: string;
  source: string;
  translation: string;

  constructor(
    message: string,
    locale: string,
    fileId: string,
    source: string,
    translation: string,
  ) {
    super(
      `[yapyak] Failed to compile message in ${fileId} (${locale})\n  source: ${source}\n  translation: ${translation}\n  reason: ${message}`,
    );
    this.locale = locale;
    this.fileId = fileId;
    this.source = source;
    this.translation = translation;
  }
}

export function compileLocale(options: CompileLocaleOptions): CompiledLocale {
  const { locale, translations, usedFiles } = options;
  const filesToInclude = usedFiles
    ? Object.keys(translations).filter((file) => usedFiles.has(file))
    : Object.keys(translations);

  const intl = createIntlInstances();
  const fileSections: string[] = [];
  const exportEntries: string[] = [];
  let messageCount = 0;

  for (const fileId of filesToInclude) {
    const fileMessages = translations[fileId];
    if (!fileMessages || Object.keys(fileMessages).length === 0) {
      continue;
    }

    const varName = `_f_${stableHash(fileId)}`;
    const lines: string[] = [];
    lines.push(`const ${varName} = {`);

    for (const [source, translation] of Object.entries(fileMessages)) {
      try {
        const fn = compileMessage(translation, locale, intl);
        lines.push(`  ${JSON.stringify(source)}: ${fn},`);
        messageCount++;
      } catch (error) {
        const reason = error instanceof Error ? error.message : String(error);
        throw new CompileError(reason, locale, fileId, source, translation);
      }
    }

    lines.push(`};`);
    fileSections.push(`// ${fileId}\n${lines.join('\n')}`);
    exportEntries.push(`  ${JSON.stringify(fileId)}: ${varName},`);
  }

  const out: string[] = [];
  out.push(`// Auto-generated by yapyak. Do not edit.`);
  out.push(
    `// Locale: ${locale} · ${messageCount} messages · ${fileSections.length} files`,
  );
  out.push('');

  if (intl.declarations.length > 0) {
    for (const declaration of intl.declarations) {
      out.push(declaration);
    }
    out.push('');
  }

  for (const section of fileSections) {
    out.push(section);
    out.push('');
  }

  out.push(`export default {`);
  for (const entry of exportEntries) {
    out.push(entry);
  }
  out.push(`};`);

  return {
    code: out.join('\n'),
    fileCount: fileSections.length,
    messageCount,
  };
}
