/**
 * Compile-time extraction and locale-file synchronization for yapyak. Consumed by `@yapyak/vite`, `@yapyak/cli`, and future build-tool integrations (webpack, esbuild) plus tooling (LSP, codemods, ESLint plugin).
 *
 * @packageDocumentation
 */

export {
  autoTranslate,
  type DiscoverLocalesOptions,
  type DiscoverLocalesResult,
  detectRenames,
  discoverLocales,
  type LocaleData,
  type LocaleFile,
  type MessagePosition,
  type MigrateLocalesOptions,
  type MigrateLocalesResult,
  migrateLocales,
  type ReadLocaleDataOptions,
  type RenameEntry,
  readLocaleData,
  readLocaleFile,
  type SyncLocaleFilesOptions,
  stringifyCanonical,
  syncLocaleFiles,
} from './catalog';
export {
  DEFAULT_EXCLUDE,
  DEFAULT_INCLUDE,
  type WalkedFile,
  type WalkSourceFilesOptions,
  walkSourceFiles,
} from './io';
export {
  type BindingTable,
  type CallSite,
  type CallSiteContext,
  createDiagnostic,
  type Diagnostic,
  type DiagnosticCode,
  discoverCalls,
  type ExtractedMessage,
  type ExtractFileRequest,
  type ExtractFileResult,
  extractFile,
  type Framework,
  type Location,
  type ParsedArguments,
  type ParsedParams,
  type Placeholder,
  type Position,
  parseArguments,
  parseAstro,
  parsePlaceholders,
  parseSvelte,
  parseVue,
  type Range,
  resolveBindings,
  resolveCallSiteContext,
  type Scope,
  type ScriptBlock,
  type TransformFileRequest,
  type TransformFileResult,
  toMessageId,
  transformFile,
  type YapyakBinding,
} from './parser';
