export function IconGlyphHash() {
  return (
    <svg
      fill="none"
      height="1em"
      shapeRendering="geometricPrecision"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth="2.25"
      viewBox="0 0 24 24"
      width="1em"
    >
      <line
        x1="4"
        x2="20"
        y1="9"
        y2="9"
      />
      <line
        x1="4"
        x2="20"
        y1="15"
        y2="15"
      />
      <line
        x1="10"
        x2="8"
        y1="3"
        y2="21"
      />
      <line
        x1="16"
        x2="14"
        y1="3"
        y2="21"
      />
    </svg>
  );
}
