const DOCS_BASE = 'https://yapyak.dev/d';

// biome-ignore assist/source/useSortedKeys: yap yap yap
export const YAP = {
  PARSER_NO_SOURCE: 'YAP0001',
  PARSER_TEMPLATE_LITERAL: 'YAP0002',
  PARSER_EMPTY_SOURCE: 'YAP0003',
  PARSER_MISSING_PARAM: 'YAP0004',
  PARSER_EXTRA_PARAM: 'YAP0005',
  PARSER_DYNAMIC_PARAMS: 'YAP0006',
  PLACEHOLDER_MALFORMED: 'YAP0007',
  PLACEHOLDER_MISSING_OTHER: 'YAP0008',
  PLACEHOLDER_UNSUPPORTED: 'YAP0009',
  PLACEHOLDER_KIND_MISMATCH: 'YAP0010',
  PLACEHOLDER_MISSING_IN_TARGET: 'YAP0011',
  PLACEHOLDER_MISSING_IN_SOURCE: 'YAP0012',
  CATALOG_INVALID_SHAPE: 'YAP0013',
  CATALOG_UNSAFE_PATH: 'YAP0014',
  CATALOG_NOT_NFC: 'YAP0015',
  CATALOG_INVALID_JSON: 'YAP0016',
  CONTEXT_NOT_LITERAL: 'YAP0017',
  CONTEXT_MIXED_USAGE: 'YAP0018',
  CONTEXT_UNUSED: 'YAP0019',
  CONTEXT_DYNAMIC_CALL: 'YAP0020',
  RUNTIME_NOT_INITIALIZED: 'YAP0021',
  RUNTIME_SSR_LEAK_RISK: 'YAP0022',
  PERSISTENCE_COOKIE_WRITER_MISSING: 'YAP0023',
  PERSISTENCE_LOCAL_STORAGE_SSR_SKIPPED: 'YAP0024',
  PERSISTENCE_LOCAL_STORAGE_WRITE_FAILED: 'YAP0025',
  PERSISTENCE_URL_SKIPPED: 'YAP0026',
  LOCALE_LISTENER_THREW: 'YAP0027',
  LOCALE_SET_IGNORED: 'YAP0028',
  LOCALE_SET_SSR_LEAK_RISK: 'YAP0029',
  LOCALE_FORCED_INVALID: 'YAP0030',
  CATALOG_LOCALE_FILE_CORRUPT: 'YAP0031',
  CATALOG_ORPHAN_CACHE_CORRUPT: 'YAP0032',
  TRANSLATE_CHUNK_FAILED: 'YAP0033',
  TRANSLATE_ENTRY_SHAPE_INVALID: 'YAP0034',
} as const;

export type YapCode = (typeof YAP)[keyof typeof YAP];

export function docsUrl(code: YapCode): string {
  return `${DOCS_BASE}/${code.toLowerCase()}`;
}

export function isYapCode(value: unknown): value is YapCode {
  if (typeof value !== 'string') {
    return false;
  }
  for (const code of Object.values(YAP)) {
    if (code === value) {
      return true;
    }
  }
  return false;
}
